---
abstract: "Use git-describe to show a repo's version"
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  Test::MockObject: 1.09
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-DescribeVersion
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Dist::Zilla::Plugin::Git::DescribeVersion:
    file: lib/Dist/Zilla/Plugin/Git/DescribeVersion.pm
    version: 0.006013
  Git::DescribeVersion:
    file: lib/Git/DescribeVersion.pm
    version: 0.006013
  Git::DescribeVersion::App:
    file: lib/Git/DescribeVersion/App.pm
    version: 0.006013
requires:
  Git::Wrapper: 0
  perl: 5.006
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Git-DescribeVersion
  repository: git://github.com/magnificent-tears/git-describeversion.git
version: 0.006013
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::DescribeVersion
      name: '@Filter/Git::DescribeVersion'
      version: 0.006012
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Filter/GitFmtChanges'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Filter/MetaNoIndex'
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.12044908
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Filter/MinimumPerl'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Filter/MetaTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Filter/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: recommends
      name: TestRecommends
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::LocalInstall
      name: LocalInstall
      version: 0.001
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102343
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102343
